added directory src
DmitrijM1983/My-Project pull request #2
Opened 2023-11-22 18:45 UTC by DmitrijM1983

2023-11-23 19:54 UTC, ufowow requested changes

2023-11-23 19:54 UTC, ufowow commented on User.php
> +     * @return array
тут возвращает массив, а ниже не исправил с void на array

2023-11-23 19:54 UTC, ufowow commented on User.php
> +            $_SESSION['result']['name'] = $result['user_name'];
предлагаю вместо $_SESSION['result'] использовать, например, $_SESSION['auth']. Кажется, так логичнее

2023-11-23 19:54 UTC, ufowow commented on reg.php
> +            <form action="src/actions/register.php" method="post">
а точно в actions должны лежать скрипты-обработчики форм? под action обычно понимают не совсем то значение, которое закладывается в название этого атрибута формы. обычно это как элемент отображения, некий метод, который отрисовывает view в паттерне MVC
я бы предложил переименовать папку для таких скриптов-обработчиков в handlers

2023-11-23 19:54 UTC, ufowow commented on reg.php
> +                <small class="text"><?=$_SESSION['validation']['password'] ?? ''?></small>
а значение $_SESSION['validation'] где-то записывается? возможно пропустил по коду. Думаю, тут достаточно было бы прописать просто текстом заголовки полей формы

2023-11-23 19:54 UTC, ufowow commented on reg.php
> +                    <button class="btn btn-info">Зарегистрироваться</button>
эта кнопка никуда не ведет?
кажется, она не отправит форму :)
нужно добавить атрибут type="submit"

2023-11-23 19:54 UTC, ufowow commented on reg.php
> +$_SESSION['old'] = [];
не очень понимаю, что это и для чего. для таких вещей, лучше оставлять комментарии :)

2023-11-23 19:54 UTC, ufowow commented on src/actions/register.php
> +require_once '../../User.php';
кажется, тут бы пригодился автолоад :)

2023-11-23 19:54 UTC, ufowow commented on reg.php
> +                    <input type="text" name="email" class="form-control" value="<?=$_SESSION['old']['email'] ?? ''?>"
я бы предложил сменить тип этого инпута на email, сейчас наверное уже все браузеры умеют валидировать поля с почтой

2023-11-23 19:54 UTC, ufowow commented on src/actions/register.php
> +if (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
вот от этой проверки можно было бы избавиться, если бы input был с типом email :)

2023-11-23 19:54 UTC, ufowow commented on src/actions/register.php
> +    $_SESSION['validation']['password'] = 'Введите пароль!';
теперь я понял, что это значит. в целом интересное решение, немного запутанное, но пусть будет. только наверное предложил бы добавить этим текстам ошибок стилизации, например, выделить красным.

2023-11-24 06:22 UTC, DmitrijM1983 commented on src/actions/register.php
> +if (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
добавил эту проверку, потому что встроенная в браузер легко пропускает, что нибудь типа qqq@www (ей главное чтобы символ @ был и текст перед и после)

2023-11-24 06:24 UTC, DmitrijM1983 commented on src/actions/register.php
> +    $_SESSION['validation']['password'] = 'Введите пароль!';
Да, текст в теге <small> красного цвета

2023-11-24 06:25 UTC, DmitrijM1983 commented on User.php
> +     * @return array
Изменил аннотацию к методу

2023-11-24 06:25 UTC, DmitrijM1983 commented on User.php
> +            $_SESSION['result']['name'] = $result['user_name'];
Сделано

2023-11-24 06:25 UTC, DmitrijM1983 commented on reg.php
> +            <form action="src/actions/register.php" method="post">
Сделано

2023-11-24 06:26 UTC, DmitrijM1983 commented on reg.php
> +                    <button class="btn btn-info">Зарегистрироваться</button>
Сделано

2023-11-24 06:28 UTC, DmitrijM1983 commented on reg.php
> +$_SESSION['old'] = [];
Очищаем сессию после перезагрузки страницы, чтобы не подсвечивались предыдущие ошибки

2023-11-28 18:43 UTC, merged